apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd.umutlabs.local
  namespace: argocd
spec:
  commonName: argocd.umutlabs.local
  dnsNames:
    - argocd.umutlabs.local
  secretName: argocd.umutlabs.local
  issuerRef:
    name: umutlabs-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io