apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../../base/

patches:
  - target:
      kind: Application
      name: grafana-app
    patch: |-
      - op: add
        path: /spec/sources/0/helm
        value:
          valueFiles:
            - $values/core/monitoring/grafana/overlays/default/grafana-values.yaml