apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: core/argocd/
      repoURL: https://github.com/umut-akkaya/umutlabs.local.git
      targetRevision: feature/automated-certificate-provisioning
    - path: bootstrap/base
      repoURL: https://github.com/umut-akkaya/umutlabs.local.git
      targetRevision: feature/automated-certificate-provisioning 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
