apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - metallb-kustomize-app.yaml
  - calico-kustomize-argo-app.yaml
  - argocd-app.yaml
  - gitlab-app.yaml
  - ../../core/openebs/overlays/only-local-pv-provisioner/
  - ../../core/traefik/overlays/default
  - ../../core/certmanager/helm/overlays/default
  - ../../core/argocd/
  - ../../core/monitoring/prometheus/overlays/default
  - ../../core/monitoring/grafana/overlays/default