apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - metallb-kustomize-app.yaml
  - calico-kustomize-argo-app.yaml
  - argocd-app.yaml
  - gitlab-app.yaml
  - core/monitoring/prometheus/overlays/default/