apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-app
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: "29.0.1"
    helm:
      releaseName: traefik
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik-v2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
