apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../../base/

patches:
  - path: patchip.yaml
  - path: patchadvertise.yaml
  - target:
      kind: IPAddressPool
      name: example
      namespace: metallb-system
    patch: |-
        - op: replace
          path: /metadata/name
          value: local-pool