apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../../base/

patches:
  - target:
      kind: Application
      name: cert-manager-app
    patch: |-
      - op: add
        path: /spec/sources/0/helm
        value:
          valuesObject:
            installCRDs: true
            crds:
              enable: true
            prometheus:
              enabled: false
    
    
