apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: default
  source:
    chart: openebs
    repoURL: https://openebs.github.io/openebs
    targetRevision: "4.1.0"
    helm:
      releaseName: openebs
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
